// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGpgBK-M-V9nm8nSdQWmSyenRIFGMGF44',
    appId: '1:895495656067:ios:348fa51b8e15a7f6f481b6',
    messagingSenderId: '895495656067',
    projectId: 'p2p-housing',
    storageBucket: 'p2p-housing.firebasestorage.app',
    iosBundleId: 'com.example.realEstateApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSUZzZgaZgimZA89m0Gevea3EL-Y_MCiU',
    appId: '1:895495656067:web:2de4d17f1c71430df481b6',
    messagingSenderId: '895495656067',
    projectId: 'p2p-housing',
    authDomain: 'p2p-housing.firebaseapp.com',
    storageBucket: 'p2p-housing.firebasestorage.app',
    measurementId: 'G-KWEYZBBRK9',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGpgBK-M-V9nm8nSdQWmSyenRIFGMGF44',
    appId: '1:895495656067:ios:348fa51b8e15a7f6f481b6',
    messagingSenderId: '895495656067',
    projectId: 'p2p-housing',
    storageBucket: 'p2p-housing.firebasestorage.app',
    iosBundleId: 'com.example.realEstateApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4oELdLChSniNbVNcSF6K8mFd1QeNnvr0',
    appId: '1:895495656067:android:fef093a76d85d911f481b6',
    messagingSenderId: '895495656067',
    projectId: 'p2p-housing',
    storageBucket: 'p2p-housing.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSUZzZgaZgimZA89m0Gevea3EL-Y_MCiU',
    appId: '1:895495656067:web:63d9d52f5f295f95f481b6',
    messagingSenderId: '895495656067',
    projectId: 'p2p-housing',
    authDomain: 'p2p-housing.firebaseapp.com',
    storageBucket: 'p2p-housing.firebasestorage.app',
    measurementId: 'G-GT70M5TCF5',
  );

}